---
  root: true
  parser: babel-eslint
  extends: airbnb/base
  env:
    node: true
    es6: true
  ecmaFeatures:
    modules: true
  rules:
    max-len: [2, 120, 4]
    eqeqeq:
      - 2
      - allow-null
    no-unused-vars: 1
    newline-after-var: 1
    no-useless-concat: 1
    prefer-template: 1
